### ISSUE TITLE
an error occured subscribing to Start Subscription

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/irisdemo-demo-htap#11]
After I started the demo and pressed `Run test` button I get `an error occured subscribing to Start Subscription` message.

In browser console I  get this error:
![image](https://user-images.githubusercontent.com/5127457/70648802-e43d1a00-1c5c-11ea-9494-c75c05aecd3b.png)

**Comment by amirsamary** [comment]
Send me the logs of the htapmaster and the workers. An exception was probably triggered there and we are not handling these just yet.

**Comment by eduard93** [comment]
Closed, the issue disappeared after moving to a server with more memory/cpu.
