### ISSUE TITLE
The link to AWS set up has been lost

### ISSUE THREAD

**Issue by wolfman0719** [intersystems-community/irisdemo-demo-htap#16]
click this link in the following section gives me not found error

1 - Running the Speed Test on AWS
Follow this link to see instructions on how to run this Speed Test on AWS comparing InterSystems IRIS with other databases such as SAP HANA and AWS Aurora.

**Comment by amirsamary** [comment]
That's odd. I just clicked it and it is working...

**Comment by wolfman0719** [comment]
Are you referencing  to  https://openexchange.intersystems.com/ICM/README.md?
I've got the same error when referencing directly to the url.

**Comment by amirsamary** [comment]
I see. It is an issue with Open Exchange. I have made that link hard coded to GitHub so it doesn't get translated to a document under open exchange.
