### ISSUE TITLE
irisdb shuts down on init with docker-compose up

### ISSUE THREAD

**Issue by renesto** [intersystems-community/irisdemo-demo-htap#24]
htapirisdb        | [FATAL] No log file specified, could not open $ISC_PACKAGE_INSTALLDIR/mgr/messages.log for reading.  Cannot log.
htapirisdb exited with code 1

This causes for speedtest on IRIS not to run

**Comment by amirsamary** [comment]
Thank you for reporting this.
I just made docker-compose.yml use a newer version of the IRIS image that fixes the issue.
