### ISSUE TITLE
Ingestion / consumption similarity

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/irisdemo-demo-htap#3]
Google definitions:
- Ingestion - the process of absorbing information
- Consumption 
    - the action of using up a resource
    - an amount of something which is used up or ingested
    - the reception of information

These words have a rather similar meaning to me.
And they both mean one directional transfer of information (inside the system).
However, in the demo the information is moved in a different directions for ingestion (inside IRIS) and consumption (outside IRIS).

I think we need to change one or both words to ease differentiation. Here's some ideas:
- INSERT / SELECT
- Ingested / Queried
- Ingested / Served
- Ingested / Returned

![изображение](https://user-images.githubusercontent.com/5127457/67812355-4a038700-fa9f-11e9-9ad9-001f6bdb6bb5.png)

**Comment by amirsamary** [comment]
I will rename "Consumed" in the UI to "Queried" to be more precise.

**Comment by pbooth01** [comment]
This issue has been resolved.
