### ISSUE TITLE
Cleanup script

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/irisdemo-demo-htap#4]
As this demo can potentially consume a lot of disk space, is `docker-compose down` enough to clean things up?

Maybe there should be an additional command to delete volumes, containers, etc. 

Just wondering.

**Comment by amirsamary** [comment]
Not really. You have to remove the containers with docker-compose rm after you are done.

**Comment by amirsamary** [comment]
Hi Eduard!

Is this answer enough for you? I mean: You should not keep the containers. You should remove them when you are done. No disk space whatsoever would be held captive.

If there is nothing more to it, please close the issue.

Kind regards,
AS

**Comment by eduard93** [comment]
Sounds good.
